image: debian:stable

stages:
  - test

debian-test:
  stage: test
  before_script:
    - apt update && apt -y install python3 python3-numpy python3-scipy python3-pip
    - pip3 install pylebedev nose
  script: # explicitly write out all cases to run
    - nosetests tests/*.py